

IF DB_ID('BDHELADERIA') IS NOT NULL
BEGIN 
USE master
DROP DATABASE  BDHELADERIA  
END


CREATE DATABASE BDHELADERIA  
	ON PRIMARY 
	(
	NAME='BDHELADERIA_mdf', FILENAME='C:\BASE\BDHELADERIA.mdf',
	SIZE=15MB,
	MAXSIZE=250MB,
	FILEGROWTH=10MB
	),	
	(
	NAME='BDHELADERIA2_mdf', FILENAME='C:\BASE\BDHELADERIA2.mdf',
	SIZE=15MB,
	MAXSIZE=250MB,
	FILEGROWTH=10MB
	)

	LOG ON 
	(
	NAME='BDHELADERIA_log', FILENAME='C:\BASE\BDHELADERIA.ldf',
	SIZE=15MB,
	MAXSIZE=250MB,
	FILEGROWTH=10MB
	)
	GO

USE BDHELADERIA 
GO

CREATE TABLE COMPRADOR 
(
CEDULA_COMPRADOR VARCHAR(10) NOT NULL ,
NOMBRE_COMPRADOR VARCHAR(30) NOT NULL ,
APELLIDO_COMPRADOR VARCHAR(30) NOT NULL ,
TELEFONO VARCHAR(10) NOT NULL ,
DIRECCION VARCHAR(50) NOT NULL ,
PRIMARY KEY (CEDULA_COMPRADOR)
);

CREATE TABLE PRODUCTO 
(
CODIGO_PRODUCTO INT NOT NULL ,
SABOR VARCHAR(30) NOT NULL ,
COSTO MONEY NOT NULL ,
PRIMARY KEY (CODIGO_PRODUCTO )
);


CREATE TABLE PEDIDO
( 
NUM_PEDIDO INT NOT NULL,
CODIGO_PRODUCTO INT NOT NULL ,
NUMERO_PRODUTOS INT NULL ,
COSTO_PEDIDO MONEY NULL,
PRIMARY KEY (NUM_PEDIDO),
FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO)
);

CREATE TABLE FACTURA
(
NUM_FACTURA INT NOT NULL ,
CEDULA_COMPRADOR VARCHAR(10) NOT NULL ,
CODIGO_PRODUCTO INT NOT NULL ,
NUM_PEDIDO INT NOT NULL ,
CANT_COMPRADA INT NOT NULL ,
TOTAL_PAGAR MONEY NULL,
PRIMARY KEY (NUM_FACTURA),
FOREIGN KEY (CEDULA_COMPRADOR) REFERENCES COMPRADOR (CEDULA_COMPRADOR),
FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO (CODIGO_PRODUCTO)

);



INSERT INTO PRODUCTO
VALUES  (1,'FRESA',2.50),
		(2,'MORA',3.00),
		(3,'CHOCOLATE',5.00),
		(4,'COCO',3.50),
		(5,'CAFE',4.00),
		(6,'PAJARO AZUL',6.00),
		(7,'PECHO AMARILLO',5.25),
		(8,'RON',4.25)					